version: "3.9"
services:
  web:
    build: .  
    ports:
      - "3005:3005"  
    environment:
      - DB_HOST="localhost"  
      - DB_PORT="localhost"  
      - DB_USER=postgres  
      - DB_PASSWORD=1234567890  
      - DB_DATABASE="prueba-kase"  

    depends_on:
      - db  
  db:
    image: postgres:14  
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=1234567890  
      - POSTGRES_DB="prueba-kase"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:  
